### ISSUE TITLE
Blurring kernel

### ISSUE THREAD

**Issue by 99991** [theophil-trippe/HDC_TUBerlin_version_1#1]
Congratulations for your excellent results on the HDC challenge!

The difficulty in this challenge seems to have been to estimate a good forward model, for which you apparently did an amazing job. I am interested in how your blurring kernel looks like. Do you have an image?

For comparison, the best we managed was
![psf_step_4](https://user-images.githubusercontent.com/18725165/140489522-ee0e4b64-d2b1-4faa-8af3-ffa503d499e2.png)

There still are some artifacts in there, but you can make out the rough shape of the aperture, so hopefully we were not too far off.

**Comment by theophil-trippe** [comment]
Thank you!

The key for us was to not only learn a blurring kernel but also a subsequent radial distortion in our forward model. That way accounting for the lens distortion.

Furthermore, subtracting the background from the images while learning the forward operator revealed to be highly beneficial. For that purpose we used the PSF sample which was provided for every step as the background. 

I have added our kernel for step 16 down below. To which step does your kernel belong?


![Screenshot 2021-11-06 at 20 30 11](https://user-images.githubusercontent.com/45559081/140621625-35e46750-1e55-4c46-8a3e-72ddcb8489a6.png)

**Comment by 99991** [comment]
Our kernel shown above was from step 4. For much higher steps, our kernel estimate was much more blurry because the optimization did not converge without a lot of regularization, but that might just be because our distortion model was not very sophisticated.

Subtracting the background sounds like a great idea. I'll keep it in mind for the future!
