### ISSUE TITLE
Possible to run without conda?

### ISSUE THREAD

**Issue by SeaDude** [theophil-trippe/HDC_TUBerlin_version_1#2]
Hello,

Thank you for your research. I'm interested in running the model and program without `conda`.

**Could I just:**
- Create a `.venv`
- `pip install` the libraries shown in `environment_nocuda.yml` (no GPU)
- Run `demo.py` then `main.py` as outlined in README?

Or does `conda` provide other functions? 

If so, how can I bypass them and just use vanilla `.venv`?

**Comment by jmaces** [comment]
Hi, that should be possible. We only used `conda` to manage the environment and install packages and never tested anything else, but other ways of creating a virtual environment and simply `pip` installing the same packages should work as well.
