### ISSUE TITLE
Different model links?

### ISSUE THREAD

**Issue by SeaDude** [theophil-trippe/HDC_TUBerlin_version_1#3]
I was unable to download the models. Any other method to get them?

- The Sharepoint link is dead
- The other one fails when trying to pull down the entire library or each individual folder
  - The file downloads over 1GB, then network fail
  - ![image](https://user-images.githubusercontent.com/8636973/211139537-56b6f6a0-6e64-4c1f-89ee-6ecd73286b97.png)

Thank you

**Comment by martin-genzel** [comment]
Indeed, the links are not working properly anymore. I've added a new one to the readme.
